# ==============================================================================
# Model 2: Homogeneous Spatial Fission (Non-Pipelined)
# ==============================================================================
TOP_MODULE = sfa_top
TB_MODULE  = sfa_top_tb
SYNTH_TCL  = synth_sfa.tcl

include ../../common.mk
