# ==============================================================================
# Model 1: Single-Tenant Dataflow Switching (Pipelined)
# ==============================================================================
TOP_MODULE = dfs_top
TB_MODULE  = dfs_top_tb
SYNTH_TCL  = synth_dfs.tcl

include ../../common.mk
