# ==============================================================================
# Model 3: Heterogeneous Fission / PolyFlow-NPU (Non-Pipelined)
# ==============================================================================
TOP_MODULE = hdf_top
TB_MODULE  = hdf_top_tb
SYNTH_TCL  = synth_hdf.tcl

include ../../common.mk
